java_import(
    name = "jna",
    jars = [
        "jna-jpms-5.12.1.jar",
        "jna-platform-jpms-5.12.1.jar",
    ],
    visibility = ["//visibility:public"],
)

java_import(
    name = "vlcj",
    jars = [
        "vlcj-4.8.2.jar",
        "vlcj-natives-4.8.1.jar"
    ],
    visibility = ["//visibility:public"],
)
