java_import(
    name = "jna",
    jars = [
        "jna-5.2.0.jar",
        "jna-platform-5.2.0.jar",
    ],
    visibility = ["//visibility:public"],
)

java_import(
    name = "vlcj",
    jars = [
        "vlcj-4.7.0.jar",
        "vlcj-natives-4.1.0.jar"
    ],
    visibility = ["//visibility:public"],
)
