java_library(
    name = "contestModel",
    srcs = glob(["**/*.java"]),
    deps = ["//ContestModel/lib:snakeyaml"],
    visibility = ["//visibility:public"],
    resources = ["org/icpc/tools/contest/model/util/messages.properties"],
)
