---
# GitLab build configuration
image: icpctools/build:servlet4

stages:
  - build
  - test
  - deploy

before_script:
  - echo "No more setup, it's all in docker"

after_script:
  - echo "Post build cleanup"

build:
  stage: build
  script:
    # - ant clean
    - ant build
    - echo $CI_JOB_ID > dist/ci_job_id.txt
  artifacts:
    paths:
      - dist/*.*
    expire_in: 1 month

test:
  stage: test
  script:
    - echo "Future tests here"

add release commit to GitHub builds repo:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git config --global user.email "bot@icpctools.org"
    - git config --global user.name "ICPC Tools bot"
  script:
    - VERSION=2.2.$(git rev-list $CI_COMMIT_SHA --count)
    - mkdir ~/builds
    - cd ~/builds
    - git clone git@github.com:icpctools/builds.git .
    - git commit --allow-empty -m "Add build $VERSION"
    - git push

deploy to CSUS:
  stage: deploy
  script:
    - apt-get install -y curl
    - export BUILDNUMBER=`echo dist/wlp.CDS-*.zip | sed 's#^dist/wlp.CDS-\([0-9\.]*\).zip*#\1#'`
    - BUILD_JOB_ID=$(cat dist/ci_job_id.txt)
    - curl "http://pc2.ecs.csus.edu/cgi-bin/grabgitlab_icpctools_artifacts.cgi?authkey=$AUTHKEY&url=https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/$BUILD_JOB_ID/artifacts&buildnumber=$BUILDNUMBER"
