java_library(
    name = "problemset",
    srcs = glob(["**/*.java"]),
    deps = [
        "//ProblemSet/lib:snakeyaml",
        "//SWTLauncher/lib:swt",
        "//SWTLauncher/src:swtLauncher",
    ],
    visibility = ["//visibility:public"],
)
