java_library(
    name = "presentationAdmin",
    srcs = glob(["**/*.java"]),
    deps = [
        "//ContestModel/src:contestModel",
        "//PresCore/src:presentCore",
        "//SWTLauncher/lib:swt",
        "//SWTLauncher/src:swtLauncher",
    ],
    resources = glob([
        "images/**/*",
    ]),
    visibility = ["//visibility:public"],
)
