java_import(
    name = "jna",
    jars = [
        "jna-5.2.0.jar",
        "jna-platform-5.2.0.jar",
    ],
    visibility = ["//visibility:public"],
)

java_import(
    name = "slf4",
    jars = [
        "slf4j-api-1.7.25.jar",
        "slf4j-nop-1.7.25.jar",
    ],
    visibility = ["//visibility:public"],
)

java_import(
    name = "vlc",
    jars = [
        "vlcj-3.12.1.jar",
    ],
    visibility = ["//visibility:public"],
)
