name = "ICPC Tools Theme"
description = "Theme used for the ICPC Tools website"
homepage = "https://tools.icpc.global"
features = ["posts", "shortcodes", "related content"]
min_version = "0.30.2"

[author]
name = "The ICPC Tools authors"
homepage = "https://github.com/icpctools"
