java_library(
    name = "presentCore",
    srcs = glob(["**/*.java"]),
    deps = [
        "//ContestModel/src:contestModel",
        "//PresCore/lib:tyrus-standalone",
    ],
    resources = glob(["*.png"]),
    visibility = ["//visibility:public"],
)
