java_import(
    name = "snakeyaml",
    jars = ["snakeyaml-1.33.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "svgSalamander",
    jars = ["svgSalamander-1.1.2.4.jar"],
    visibility = ["//visibility:public"],
)
