- id: admin
  username: admin
  password: adm1n
  type: admin
- id: presAdmin
  username: admpresAdminin
  password: padm1n
  type: presAdmin
- id: blue
  username: blue
  password: bl3u
  type: staff
- id: balloon
  username: balloon
  password: balloonPr1nter
  type: balloon
- id: presentation
  username: presentation
  password: presentat1on
  type: public
- id: myicpc
  username: myicpc
  password: my1cpc
  type: analyst
- id: live
  username: live
  password: l1ve
  type: analyst
- id: team1
  username: team1
  password: t3am
  type: team
  team_id: '1'