baseURL = "https://icpctools.org/"
languageCode = "en-us"
title = "The ICPC Tools"
description = "The ICPC Tools are a variety of tools implemented by the  ICPC Tools Group for use at the ICPC World Finals and other programming contests"
theme = "icpctools"
googleAnalytics = "UA-65166360-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
