name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: icpctools/builder
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Build
        run: ant build
      - name: Add run ID
        run: echo $GITHUB_RUN_ID > dist/github_run_id.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/*
