name: Push Builder Docker Image
on:
  push:
    branches:
      - main
    paths:
      - build/builder.Dockerfile
jobs:
  push-builder-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Builder Docker image
        run: |
          cd build
          docker build -t ghcr.io/icpctools/builder:latest -f builder.Dockerfile .
          docker push ghcr.io/icpctools/builder:latest
